#sonar

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -39,8 +39,9 @@ jobs:
           test
       - name: Run build-wrapper
         run: |
-          build-wrapper-linux-x86-64 --help
-          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Coverage
+          cd build || die
+          build-wrapper-linux-x86-64 --out-dir . make VERBOSE=1 || die "Build wrapper failed"
+          cd ..
       - name: Run sonar-scanner
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -48,19 +49,18 @@ jobs:
         run: >
           sonar-scanner
           -X
-          --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
+          --define sonar.cfamily.build-wrapper-output="build"
           --define sonar.organization=opencyphal-garage
           --define sonar.projectKey=OpenCyphal-Garage_libcyphal
           --define sonar.projectName=libcyphal
           --define sonar.projectVersion=1.0
-          --define sonar.sources=include,test/unittest/sonar.cpp
+          --define sonar.sources=include
           --define sonar.tests=test/unittest,docs/examples
           --define sonar.test.inclusions=test_*.cpp,example_*.cpp
           --define sonar.sourceEncoding=UTF-8
           --define sonar.host.url=https://sonarcloud.io
           --define sonar.cfamily.ignoreHeaderComments=false
-          --define sonar.coverage.exclusions="test/unittest/**/*,docs/examples/**/*,**/sonar.cpp"
-          --define sonar.cpd.exclusions="test/unittest/**/*,docs/examples/**/*,**/sonar.cpp"
+          --define sonar.coverage.exclusions="test/unittest/**/*,docs/examples/**/*"
+          --define sonar.cpd.exclusions="test/unittest/**/*,docs/examples/**/*"
           --define sonar.cfamily.compile-commands="build/compile_commands.json"
           --define sonar.cfamily.reportingCppStandardOverride=c++14
-          --define sonar.coverageReportPaths="build/test/unittest/coverage.xml,build/docs/examples/coverage.xml"
